---
- name: NGINX | Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
  notify: Start nginx
- name: Nginx | Create general config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Reload nginx
